name: Run Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Select build environment (dev, qa, uat, prod)"
        required: true
        type: choice
        default: "dev" # Default to 'dev' if no input is given
        options:
          - dev
          - qa
          - uat
          - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --ci --coverage

      - name: Run linter
        run: npm run lint  # Assuming you have a lint script in your package.json

      - name: Build
        run: npm run build:${{ github.event.inputs.environment }}  # Use the selected environment
        if: github.event_name == 'workflow_dispatch'  # Only use input for manual runs
  
      - name: Deploy to GitHub Pages
        if: success()  # Only deploy if the build step succeeded
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
          publish_dir: ./build   
